# Netlify
[build]
  publish = "."

[[headers]]
  for = "/products.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
